name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install
        run: ./emsdk install latest

      - name: Activate
        run: ./emsdk activate latest

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled
          path: ./
